### PR TITLE
added an example vagrant challenge using puppet

### PR DESCRIPTION
**Pull request by northdpole**
added an example challenge that uses puppet to help you with development, it doesn't have any flags though, I could add them if you want.
If you there's anything wrong with it or if it doesn't quite work for you feel free to remove it ;)

### CODE REVIEW

**Comment by mebjas** [comment]
One thing I was wondering is, what if we want to put a flag in db like in case of sql injection. How do we generate that randomly?

One option is to ask challenge developer to add a php script that pushes the required flag to db, and add a shell provisioner to run that script once, and then delete it.

**Comment by northdpole** [comment]
or the flags could be in a file with the file path provided in the challenge xml, then we open the file, randomize the flag and the challenge is responsible for setting itself up.

The php solution sounds too restrictive

**Comment by mebjas** [comment]
yeah, developer can do that!

----------------------------------------------------------------------------
Kind Regards,
Minhaz | My Projects <http://cistoner.org/projects> | M
<http://cistoner.org/minhaz/>y blog <http://blog.minhazav.me/>

**Comment by northdpole** [comment]
Or we could add a shell command which generates the flag and runs via puppet, then the flag can be stored in a variable

**Pull request merged**
